name = "FacsimileBuilders"
uuid = "51afb9e0-fec5-4c9c-a749-28047e6f0de5"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "0.27"
DocStringExtensions = "0.8"
julia = "1"
